/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_xinjianchi_jni_first_HelloWorld */

#ifndef _Included_com_example_xinjianchi_jni_first_HelloWorld
#define _Included_com_example_xinjianchi_jni_first_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_xinjianchi_jni_first_HelloWorld
 * Method:    helloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_xinjianchi_jni_1first_HelloWorld_helloWorld
  (JNIEnv *, jclass);

/*
 * Class:     com_example_xinjianchi_jni_first_HelloWorld
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_xinjianchi_jni_1first_HelloWorld_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
